### ISSUE TITLE
Additional alternative: destructuring spread

### ISSUE THREAD

**Issue by mrjacobbloom** [devlato/tc39-proposal-key-exclusion-syntax-in-object-spread#1]
One existing syntax that you don't mention in your Alternatives section is this:

```js
const { propertyIDontWant, ...newObject } = origObject;
```

**Comment by devlato** [comment]
Thanks @mrjacobbloom, will add it!

**Comment by devlato** [comment]
@mrjacobbloom thanks for suggesting, I've updated the README. I'll close this issue, and please feel free to re-open it if there's something else.
