### ISSUE TITLE
computed removed key

### ISSUE THREAD

**Issue by Jack-Works** [devlato/tc39-proposal-key-exclusion-syntax-in-object-spread#2]
If I understand it correctly, is it in this form?

```js
const x = { ...y, -[computed()] }
```

**Comment by devlato** [comment]
@Jack-Works yep 👍

**Comment by devlato** [comment]
@Jack-Works does it fits you, or do you have any suggestions?

**Comment by Jack-Works** [comment]
Never mind, just a clarifying question. thanks

**Comment by devlato** [comment]
@Jack-Works no worries! Please let me know if you have other questions and/or the README is incomplete 🙂
