### ISSUE TITLE
Why order independence?

### ISSUE THREAD

**Issue by ckknight** [devlato/tc39-proposal-key-exclusion-syntax-in-object-spread#3]
I don't see the purpose of order independence and frankly find it surprising, as it acts differently than what I would expect with normal object and spread syntax.

```js
const obj = {
  ...alpha,
  -key,
  ...bravo,
};
```

I would expect to roughly transpile to:
```js
const obj = Object.assign({}, alpha);
delete obj.key;
Object.assign(obj, bravo);
```

Which would allow for `bravo` to add back the `key` property if it has one.

**Comment by ljharb** [comment]
+1, I think that order *must* matter, just like it currently does for object literal syntax.

**Comment by devlato** [comment]
@ckknight @ljharb my initial thinking was to make it order independent, based on the typical use case where you'd want to remove a key from the result, and the order-dependent implementation doesn't seem a lot different. Let's assume we have this code:
```ts
const obj = {
  ...alpha,
  -key,
  ...bravo,
};
```
1. If bravo has key `'key'`, removing key before merging with `bravo` doesn't make a real difference, as the value from `bravo['key']` will just override `obj['key']`.
2. if bravo doesn't have key `'key'`, removing the key would just remove it from the result. 
Thus, we *could* made this operation order-dependent, but there wouldn't be any real difference.

**Comment by ljharb** [comment]
That’s actually a fair point - what if you want key from alpha but not from bravo? There’s no way to do it. It kind of seems like the subtraction is really conceptually a part of each individual spread - not the object it’s being spread into.

**Comment by devlato** [comment]
> what if you want key from alpha but not from bravo?

@ljharb I'd say in that case, old good spread syntax still works:
```ts
const obj = {
  ...alpha,
  ...bravo,
  key: alpha.key,
};
```
WDYT?

**Comment by ljharb** [comment]
That evaluates a getter on alpha twice.

**Comment by devlato** [comment]
@ljharb soooo this?
```ts
const obj = {
  ...({ ...alpha, -key }),
  ...bravo,
};
```
----------
I mean, something like this:
```ts
const obj = {
  ...alpha,
  ...bravo,
  -key,
};
```
doesn't seem clear and straightforward for expressing your use case, to be honest.

**Comment by ljharb** [comment]
I agree the nested spreads “solves” it, but I’m saying that i think the subtraction syntax needs to be somehow tied to the thing being spreaded out, not the thing receiving the properties.

Put another way, “-key” only makes sense when it’s attached to one specific spread/object - ie, “...a” or “...b”.

**Comment by ckknight** [comment]
One alternative I can see to nip this in the bud is to require that the omits be at the end of the object and not allow any further property additions or spreads.

**Comment by ljharb** [comment]
That would resolve the ambiguity, but would imo substantially limit the feature's usefulness.

**Comment by devlato** [comment]
@ljharb what syntax would you suggest? 🙂
I don't think order dependence would help solve your use case, as object spread is straightforwardly left-to-right, and your case implies applying the minus operator to the adjacent preceding item in the spread (which looks more like right-to-left and isn't intuitive).

I mean if in this:
```ts
const obj = {
  ...alpha,
  ...bravo,
  -key,
};
```
we made `-key` apply to the previous argument in object spread (which's `bravo`) instead of the result computed to that point (`{...alpha, ...bravo }`), is different from the way the object spread itself works and thus could be less intuitive.

**Comment by ljharb** [comment]
tbh, i can’t think of a good one. Essentially, what seems to make the most sense is something that’s part of the spread syntax itself, but there’s no room there for anything practical.

**Comment by ghost** [comment]
Should only the minus operator be order dependant?
It seems like the plus operator would be completely useless otherwise.

**Comment by devlato** [comment]
@CrimsonCodes0 probably; technically, this is why initially, I suggested making both order independent, as the results would still be the same

**Comment by devlato** [comment]
Thanks, folks—the question has been addressed in the new edition of the proposal.

**Comment by devlato** [comment]
Thanks, folks—the question has been addressed in the new edition of the proposal.
